# Generated by Django 4.2.22 on 2025-06-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcu_estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoTCU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Finalizado', 'Finalizado'), ('Pendiente', 'Pendiente')], max_length=20)),
            ],
        ),
    ]
