# Generated by Django 4.2.22 on 2025-06-07 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tcu_estudiantes', '0002_periodotcu'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcuestudiante',
            name='periodo_tcu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tcu_estudiantes.periodotcu'),
            preserve_default=False,
        ),
    ]
